import Link from "next/link";
import {
  Target, Eye, ShieldCheck, Lock, MessageSquare, Zap, Gauge,
  Linkedin, Github, Mail, MapPin, Briefcase, GraduationCap,
  ArrowRight, type LucideIcon,
} from "lucide-react";
import { Panel, CardBody } from "@/components/ui/card";
import { buttonVariants } from "@/components/ui/button-variants";
import { cn } from "@/lib/utils";

const STATS: [string, string][] = [
  ["11", "analysis modules"],
  ["<5s", "to first insight"],
  ["0", "API keys required"],
];

const FOUNDER = {
  name: "Jainam Gogree",
  title: "Founder",
  subtitle: "Data & Business Analyst",
  tagline: "Turning signal into decisions.",
  location: "San Francisco Bay Area, CA",
  linkedin: "https://www.linkedin.com/in/jainamgogree/",
  github: "https://github.com/karmic05",
  email: "jainam.gogree05@gmail.com",
  bio: [
    "Jainam Gogree is the founder of AnalystAI. His path to analytics started in electronics engineering, detoured through an MBA in marketing, and landed squarely in data — where signal-processing meets consumer behavior.",
    "He is a pragmatic analyst, not a model-chaser: reach for the simplest explanation the data supports, and treat stakeholder storytelling as a first-class deliverable. That philosophy is why AnalystAI computes every number with a deterministic engine and lets the AI only write the prose around it.",
    "Before AnalystAI, Jainam built automated ingestion pipelines and Power BI dashboards at ITSYS Solutions and drove marketing analytics at Runwal Group. He now leads the product and the analysis engine behind AnalystAI while completing his M.S. in Business Analytics at Hult International Business School.",
  ],
  experience: [
    {
      role: "Business Analyst — Data Analytics & BI",
      org: "ITSYS Solutions, Mumbai",
      period: "Oct 2023 – Sep 2025",
      impact: "Automated Python/SQL ingestion across 50+ sources; shipped 30+ Power BI dashboards; built pricing and geospatial site-selection models supporting a $5M SaaS pipeline.",
    },
    {
      role: "Marketing Analyst",
      org: "Runwal Group, Mumbai",
      period: "Feb 2023 – May 2024",
      impact: "Salesforce ETL pipelines, customer segmentation, and predictive lead scoring — a 45% lift in qualified leads and $10M+ in incremental revenue.",
    },
    {
      role: "Team Lead — KJSCE Robocon",
      org: "Mumbai University",
      period: "Aug 2019 – Sep 2021",
      impact: "Led a 20-member cross-functional team; All India Rank 5 at ABU ROBOCON 2019 & 2020.",
    },
  ],
  education: [
    { degree: "M.S. in Business Analytics", school: "Hult International Business School, Boston" },
    { degree: "MBA, Marketing", school: "IFHE, Hyderabad" },
    { degree: "B.Tech, Electronics Engineering", school: "Mumbai University" },
  ],
  metrics: [
    ["$5M", "SaaS pipeline built"],
    ["$10M+", "incremental revenue"],
    ["30+", "dashboards shipped"],
    ["20+", "analytics projects"],
  ] as [string, string][],
};

const VALUES: { icon: LucideIcon; title: string; body: string; tone: string }[] = [
  {
    icon: ShieldCheck,
    title: "Numbers you can trust",
    body: "Every metric, insight, and forecast is computed by a deterministic analysis engine — never generated by a language model. The analysis cannot be hallucinated.",
    tone: "var(--green)",
  },
  {
    icon: Lock,
    title: "Private by default",
    body: "Your data stays in your browser. The optional AI layer carries only schema and aggregate statistics — raw rows never leave the page.",
    tone: "var(--cyan)",
  },
  {
    icon: MessageSquare,
    title: "Analysis for everyone",
    body: "No SQL, no spreadsheets, no data team. Ask a question in plain English and receive an answer grounded in your real numbers.",
    tone: "var(--purple)",
  },
  {
    icon: Zap,
    title: "Fast, offline, and open",
    body: "The core analytical loop runs in the browser with no API key required. Add a key only when you want richer, LLM-grade prose.",
    tone: "var(--amber)",
  },
  {
    icon: Gauge,
    title: "Measured, not magical",
    body: "Forecast accuracy is scored with a holdout MAPE and trend fit (R²), so you always know how far to trust a projection before you act on it.",
    tone: "var(--magenta)",
  },
  {
    icon: Target,
    title: "Decisions first, tooling second",
    body: "AnalystAI exists to accelerate decisions, not to sell infrastructure. The output is a clear story and a board-ready report — the software is the means.",
    tone: "var(--green)",
  },
];

export function About() {
  return (
    <div>
      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 radial-glow" />
        <div className="relative mx-auto max-w-4xl px-5 pb-20 pt-20 text-center lg:pt-28">
          <div className="eyebrow">// about analystai</div>
          <h1 className="mx-auto mt-5 max-w-3xl text-4xl font-bold leading-[1.05] tracking-tight sm:text-5xl lg:text-[3.5rem]">
            On a mission to put an analyst on every operator&apos;s desk.
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-muted">
            AnalystAI is an AI business analyst that turns a spreadsheet into a story — profiling
            data, surfacing the insights that matter, forecasting the next period, and writing the
            board report in seconds.
          </p>
          <p className="mt-6 font-script text-2xl text-purple/90">— built for operators, founders &amp; analysts</p>

          <dl className="mx-auto mt-12 grid max-w-lg grid-cols-3 gap-4">
            {STATS.map(([n, l]) => (
              <div key={l} className="neu rounded-2xl p-4">
                <div className="font-display text-3xl font-bold text-gradient">{n}</div>
                <div className="mt-1 text-xs text-muted">{l}</div>
              </div>
            ))}
          </dl>
        </div>
      </section>

      {/* Mission & Vision */}
      <section className="mx-auto max-w-7xl px-5 py-16">
        <div className="grid gap-4 md:grid-cols-2">
          <Panel className="card-hover">
            <CardBody>
              <div className="mb-4 grid h-11 w-11 place-items-center rounded-xl" style={{ background: "color-mix(in srgb, var(--green) 13%, transparent)", color: "var(--green)" }}>
                <Target size={20} />
              </div>
              <div className="eyebrow">mission</div>
              <h2 className="mt-2 text-2xl font-bold tracking-tight text-ink">Give every operator an instant analyst.</h2>
              <p className="mt-3 leading-relaxed text-muted">
                AnalystAI exists to give every operator, founder, and analyst an instant business
                analyst — one that turns raw data into insights, dashboards, forecasts, and
                board-ready reports in seconds, without SQL, spreadsheets, or a data team. The
                people closest to a business&apos;s decisions should never be far from its numbers.
              </p>
            </CardBody>
          </Panel>

          <Panel className="card-hover">
            <CardBody>
              <div className="mb-4 grid h-11 w-11 place-items-center rounded-xl" style={{ background: "color-mix(in srgb, var(--purple) 13%, transparent)", color: "var(--purple)" }}>
                <Eye size={20} />
              </div>
              <div className="eyebrow">vision</div>
              <h2 className="mt-2 text-2xl font-bold tracking-tight text-ink">A trusted analyst on demand, for everyone.</h2>
              <p className="mt-3 leading-relaxed text-muted">
                A world where asking a question of your data is as easy as asking a colleague —
                where every decision-maker has a capable analyst one prompt away, and the numbers
                that drive a business are never gated behind a specialty, a queue, or a dashboard
                no one has time to build.
              </p>
            </CardBody>
          </Panel>
        </div>
      </section>

      {/* Story */}
      <section className="relative border-y border-line bg-surface-2/40">
        <div className="absolute inset-0 grid-bg opacity-40" />
        <div className="relative mx-auto max-w-3xl px-5 py-24">
          <div className="eyebrow">// our story</div>
          <h2 className="mt-4 text-3xl font-bold tracking-tight text-ink sm:text-4xl">Why we built AnalystAI</h2>
          <div className="mt-6 space-y-4 text-lg leading-relaxed text-muted">
            <p>
              AnalystAI began with a familiar frustration: the people closest to a business&apos;s
              decisions are rarely the people closest to its data. Spreadsheets intimidate, SQL is a
              specialty, and data teams are stretched thin. The path from a raw file to a board-ready
              report ran through queues, exports, and weeks of waiting.
            </p>
            <p>
              We believed that path could be a single prompt. So we built AnalystAI as two working
              parts: a deterministic analysis engine that computes every number you can trust, and an
              AI layer that writes the prose around it. The numbers can never be hallucinated, and the
              narrative reads like an analyst wrote it — because, in a sense, one did.
            </p>
            <p>
              Today the core loop runs in your browser, privately and offline, with an optional LLM
              for richer writing. Tomorrow it connects to your warehouse, your database, and the rest
              of your stack — but the promise stays the same: ask a question, get a defensible answer,
              and the report to go with it.
            </p>
          </div>
        </div>
      </section>

      {/* Values */}
      <section className="mx-auto max-w-7xl px-5 py-24">
        <div className="max-w-2xl">
          <div className="eyebrow">// what we believe</div>
          <h2 className="mt-4 text-3xl font-bold tracking-tight text-ink sm:text-4xl">Principles that shape every decision.</h2>
        </div>
        <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {VALUES.map((v) => (
            <Panel key={v.title} className="card-hover rounded-2xl p-6">
              <div className="mb-4 grid h-11 w-11 place-items-center rounded-xl" style={{ background: `color-mix(in srgb, ${v.tone} 13%, transparent)`, color: v.tone }}>
                <v.icon size={20} />
              </div>
              <h3 className="text-base font-semibold text-ink">{v.title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-muted">{v.body}</p>
            </Panel>
          ))}
        </div>
      </section>

      {/* Founder */}
      <section className="mx-auto max-w-6xl px-5 pb-24">
        <div className="max-w-2xl">
          <div className="eyebrow">// founder</div>
          <h2 className="mt-4 text-3xl font-bold tracking-tight text-ink sm:text-4xl">Founder</h2>
        </div>

        <Panel className="mt-10 rounded-2xl">
          <div className="grid gap-8 p-6 sm:p-8 md:grid-cols-[260px_1fr] md:gap-10">
            {/* Identity */}
            <div className="flex flex-col items-center text-center md:items-start md:text-left">
              <div className="grid h-24 w-24 place-items-center rounded-2xl bg-brand-gradient font-display text-3xl font-bold text-white shadow-sm">
                JG
              </div>
              <h3 className="mt-5 text-2xl font-bold tracking-tight text-ink">{FOUNDER.name}</h3>
              <div className="mt-1 font-mono text-xs uppercase tracking-widest text-green">{FOUNDER.title}</div>
              <div className="mt-0.5 text-sm text-muted">{FOUNDER.subtitle}</div>
              <p className="mt-4 font-script text-2xl text-purple/90">{FOUNDER.tagline}</p>
              <div className="mt-4 flex items-center gap-1.5 text-xs text-muted">
                <MapPin size={13} className="text-cyan" /> {FOUNDER.location}
              </div>
              <div className="mt-5 flex w-full flex-wrap gap-2 md:flex-col">
                <a
                  href={FOUNDER.linkedin}
                  target="_blank"
                  rel="noreferrer"
                  className={cn(buttonVariants({ variant: "outline", size: "sm" }), "w-full md:w-auto")}
                >
                  <Linkedin size={15} /> LinkedIn
                </a>
                <a
                  href={FOUNDER.github}
                  target="_blank"
                  rel="noreferrer"
                  className={cn(buttonVariants({ variant: "outline", size: "sm" }), "w-full md:w-auto")}
                >
                  <Github size={15} /> GitHub
                </a>
                <a
                  href={`mailto:${FOUNDER.email}`}
                  className={cn(buttonVariants({ variant: "outline", size: "sm" }), "w-full md:w-auto")}
                >
                  <Mail size={15} /> Email
                </a>
              </div>
            </div>

            {/* Profile */}
            <div className="space-y-7">
              <div className="space-y-3 leading-relaxed text-muted">
                {FOUNDER.bio.map((p, i) => (
                  <p key={i}>{p}</p>
                ))}
              </div>

              <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
                {FOUNDER.metrics.map(([n, l]) => (
                  <div key={l} className="neu rounded-xl p-3">
                    <div className="font-display text-xl font-bold text-gradient">{n}</div>
                    <div className="mt-0.5 text-[11px] leading-tight text-muted">{l}</div>
                  </div>
                ))}
              </div>

              <div>
                <div className="eyebrow mb-3">experience</div>
                <ul className="space-y-4">
                  {FOUNDER.experience.map((e) => (
                    <li key={e.role} className="flex gap-3">
                      <Briefcase size={16} className="mt-0.5 shrink-0 text-cyan" />
                      <div>
                        <div className="text-sm font-semibold text-ink">{e.role}</div>
                        <div className="font-mono text-[11px] text-muted">{e.org} · {e.period}</div>
                        <div className="mt-0.5 text-sm leading-relaxed text-muted">{e.impact}</div>
                      </div>
                    </li>
                  ))}
                </ul>
              </div>

              <div>
                <div className="eyebrow mb-3">education</div>
                <ul className="space-y-2.5">
                  {FOUNDER.education.map((e) => (
                    <li key={e.degree} className="flex gap-3">
                      <GraduationCap size={16} className="mt-0.5 shrink-0 text-purple" />
                      <div>
                        <div className="text-sm font-semibold text-ink">{e.degree}</div>
                        <div className="font-mono text-[11px] text-muted">{e.school}</div>
                      </div>
                    </li>
                  ))}
                </ul>
              </div>

              <p className="font-script text-3xl text-purple/90">{FOUNDER.name}</p>
            </div>
          </div>
        </Panel>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-7xl px-5 pb-24">
        <Panel className="flex flex-col items-center gap-4 rounded-2xl p-8 text-center sm:flex-row sm:justify-between sm:text-left">
          <div>
            <h3 className="text-lg font-semibold text-ink">Put an analyst on your desk.</h3>
            <p className="mt-1 text-sm text-muted">
              Load the built-in sample and run the full pipeline in the Studio. No signup needed.
            </p>
          </div>
          <div className="flex shrink-0 items-center gap-3">
            <Link href="/how" className={cn(buttonVariants({ variant: "ghost", size: "md" }))}>
              See how it works
            </Link>
            <Link href="/studio" className={cn(buttonVariants({ variant: "accent", size: "lg" }))}>
              Launch the Studio <ArrowRight size={16} />
            </Link>
          </div>
        </Panel>
      </section>
    </div>
  );
}
